# Generated by Django 6.0.3 on 2026-04-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pessoa",
            new_name="utilizador",
        ),
    ]
