# Generated by Django 6.0.4 on 2026-04-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_pessoa_utilizador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
                ("link_lusofona", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data", models.DateField()),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="licenciaturas/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data", models.DateField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem"),
                            ("framework", "Framework"),
                            ("bd", "Base de Dados"),
                            ("ferramenta", "Ferramenta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[(1, "Baixo"), (2, "Médio"), (3, "Alto")]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="utilizador",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="utilizadores/"),
        ),
        migrations.AlterField(
            model_name="utilizador",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[(1, "Básico"), (2, "Intermédio"), (3, "Avançado")]
                    ),
                ),
                (
                    "formacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencias",
                        to="app.formacao",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencias",
                        to="app.tecnologia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("resumo", models.TextField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="tfc/")),
                (
                    "docente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tfcs",
                        to="app.docente",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(related_name="tfcs", to="app.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("apresentacao", models.TextField()),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "1º Semestre"), (2, "2º Semestre")]
                    ),
                ),
                ("ects", models.IntegerField()),
                (
                    "docentes",
                    models.ManyToManyField(related_name="ucs", to="app.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="app.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="ucs/projetos/"),
                ),
                ("github", models.URLField(blank=True)),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="app.unidadecurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemUC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="ucs/imagens/")),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="app.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
