# Generated by Django 6.0.4 on 2026-04-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_docente_formacao_licenciatura_makingof_tecnologia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemuc",
            name="uc",
        ),
        migrations.DeleteModel(
            name="utilizador",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/imagens/"),
        ),
        migrations.DeleteModel(
            name="ImagemUC",
        ),
    ]
