# Generated by Django 6.0.4 on 2026-04-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_imagemuc_uc_delete_utilizador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="app/docentes/"),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/licenciaturas/"
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="app/makingof/"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="app/projetos/"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/tecnologias/"
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="app/tfc/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="app/ucs/"),
        ),
    ]
