# Generated by Django 6.0.4 on 2026-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_docente_imagem_alter_licenciatura_imagem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnologia",
            name="tipo",
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="nivel_interesse",
            field=models.IntegerField(
                choices=[(1, "Baixo"), (2, "Médio"), (3, "Alto")], null=True
            ),
        ),
    ]
