# Generated by Django 6.0.4 on 2026-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_tecnologia_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="nome",
            field=models.CharField(max_length=300),
        ),
    ]
