# Generated by Django 6.0.5 on 2026-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_artigo_comentario"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=100)),
                ("apelido", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
