# Generated by Django 6.0.5 on 2026-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="comentario",
            name="autor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="comentario",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
